// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPYtlXvegSk6_eSEGUTp8y2UcI6elZrsc',
    appId: '1:39130238863:web:0076a869bad76b4a7745fa',
    messagingSenderId: '39130238863',
    projectId: 'pancakesff',
    authDomain: 'pancakesff.firebaseapp.com',
    storageBucket: 'pancakesff.appspot.com',
    measurementId: 'G-C5Z9PMTMF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGgIShdvh3o-5Xy-fRH8fXcSkMJlVfNZc',
    appId: '1:39130238863:android:16941c9bc0a6c0a57745fa',
    messagingSenderId: '39130238863',
    projectId: 'pancakesff',
    storageBucket: 'pancakesff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBd13cBBmn6OOQHNX7YNkoie8LSgK0CxU',
    appId: '1:39130238863:ios:f9f89c086a9338f07745fa',
    messagingSenderId: '39130238863',
    projectId: 'pancakesff',
    storageBucket: 'pancakesff.appspot.com',
    iosClientId: '39130238863-dqprehbkv2npcl1oep7od3lh32ev4ig4.apps.googleusercontent.com',
    iosBundleId: 'com.coducode.marketingTools',
  );
}
